# Generated by Django 6.0.5 on 2026-05-21 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200)),
                ('cliente', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('revision', 'Revisión'), ('recepcion', 'Recepción'), ('diseno', 'Diseño'), ('corte', 'Corte'), ('finalizado', 'Finalizado'), ('entregado', 'Entregado')], default='revision', max_length=20)),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adelanto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tiempo_estimado', models.IntegerField(help_text='Tiempo en minutos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('alarma_activada', models.BooleanField(default=False)),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('revision', 'Revisión'), ('recepcion', 'Recepción'), ('diseno', 'Diseño'), ('corte', 'Corte'), ('finalizado', 'Finalizado'), ('entregado', 'Entregado')], max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='menu.ordentrabajo')),
            ],
        ),
    ]
